# Keys an island image into assets/islands/<name>.png (360px, real alpha).
# Handles real alpha, flat colour backgrounds (magenta) and painted
# checkerboards. Then regenerates src/data/islandShapes.mjs: each island's
# outline as 48 radii (fraction of half-size) round its centre, so the arena
# can stamp matching collision without loading images.
# usage: python3 tools/key-island.py [<name> <image>]...   (no args: shapes only)
import sys, os, glob, json, numpy as np
from PIL import Image
from scipy import ndimage
ROOT=os.path.join(os.path.dirname(os.path.abspath(__file__)),'..')
OUT=os.path.join(ROOT,'assets','islands')
def key(src):
    im=Image.open(src); a=np.asarray(im.convert('RGBA')).astype(float)
    rgb=a[...,:3]
    if im.mode=='RGBA' and a[...,3].min()<10:
        core=a[...,3]>235
    else:
        e=np.concatenate([rgb[:6].reshape(-1,3),rgb[-6:].reshape(-1,3),rgb[:,:6].reshape(-1,3),rgb[:,-6:].reshape(-1,3)])
        mx,mn=rgb.max(-1),rgb.min(-1)
        sat=mx-mn
        if np.median(e.max(-1)-e.min(-1))>120:   # flat saturated colour (magenta)
            bg=np.median(e,axis=0); near=np.sqrt(((rgb-bg)**2).sum(-1))<90
        else:                                    # painted checkerboard
            near=(sat<22)&(mn>120)
        lab,_=ndimage.label(near)
        edge=set(np.unique(np.concatenate([lab[0],lab[-1],lab[:,0],lab[:,-1]])))-{0}
        core=~np.isin(lab,list(edge))
    core=ndimage.binary_opening(core,iterations=3)
    lab,n=ndimage.label(core); sizes=ndimage.sum(core,lab,range(1,n+1))
    core=lab==(1+int(np.argmax(sizes)))
    core=ndimage.binary_fill_holes(core); core=ndimage.binary_erosion(core,iterations=2)
    alpha=ndimage.gaussian_filter(core.astype(float),0.8)
    out=np.dstack([rgb,alpha*255]).astype(np.uint8)
    ys,xs=np.where(alpha>0.05); img=Image.fromarray(out).crop((xs.min(),ys.min(),xs.max()+1,ys.max()+1))
    s=360/max(img.size); return img.resize((round(img.width*s),round(img.height*s)),Image.LANCZOS)
args=sys.argv[1:]
for i in range(0,len(args),2):
    img=key(args[i+1]); img.save(os.path.join(OUT,args[i]+'.png'),optimize=True); print(args[i],img.size)
# Outline radii, measured from the image centre, as a fraction of max(w,h)/2.
shapes={}
for f in sorted(glob.glob(os.path.join(OUT,'*.png'))):
    name=os.path.basename(f)[:-4]
    al=np.asarray(Image.open(f).convert('RGBA'))[...,3]>128
    h,w=al.shape; cx,cy=w/2,h/2; half=max(w,h)/2; radii=[]
    for k in range(48):
        t=k/48*2*np.pi; r=0
        for s in np.arange(0,half*1.5,1):
            x,y=int(cx+np.cos(t)*s),int(cy+np.sin(t)*s)
            if 0<=x<w and 0<=y<h and al[y,x]: r=s
        radii.append(round(r/half,3))
    shapes[name]={'w':round(w/max(w,h),3),'h':round(h/max(w,h),3),'r':radii}
js='// Generated by tools/key-island.py: each island image\'s outline as 48\n// radii (fraction of half its longest side), clockwise from +x.\nexport const ISLAND_SHAPES = '+json.dumps(shapes,separators=(',',':'))+';\n'
open(os.path.join(ROOT,'src','data','islandShapes.mjs'),'w').write(js); print(len(shapes),'shapes')
